/*BDAS1*/

-- TABULKY
DROP TABLE FIRMY;
DROP TABLE OSOBY;
DROP TABLE REZERVACE;
DROP TABLE ZAJEMCI;
DROP TABLE MISTNOSTI;
DROP TABLE INVENTARE;
DROP TABLE PRISLUSENSTVI;
DROP TABLE SKUPINY_VLASTNOSTI;
DROP TABLE STAVY;
DROP TABLE UCELY;
DROP TABLE VELIKOSTI;
DROP TABLE UMISTENI;
DROP TABLE PATRA;
-- SEKVENCE
DROP SEQUENCE S_MISTNOSTI;
DROP SEQUENCE S_PATRA;
DROP SEQUENCE S_PRISLUSENSTVI;
DROP SEQUENCE S_REZERVACE;
DROP SEQUENCE S_SKUPINY;
DROP SEQUENCE S_STAVY;
DROP SEQUENCE S_UCELY;
DROP SEQUENCE S_UMISTENI;
DROP SEQUENCE S_VELIKOSTI;
DROP SEQUENCE S_ZAJEMCI;
-- TRIGGERY
DROP TRIGGER ARC_FKARC_1_FIRMY;
DROP TRIGGER ARC_FKARC_1_OSOBY;
DROP TRIGGER T_MISTNOSTI_ID;
DROP TRIGGER T_PATRA_ID;
DROP TRIGGER T_PRISLUSENSTVI_ID;
DROP TRIGGER T_REZERVACE_ID;
DROP TRIGGER T_SKUPINY_ID;
DROP TRIGGER T_STAVY_ID;
DROP TRIGGER T_UCELY_ID;
DROP TRIGGER T_UMISTENI_ID;
DROP TRIGGER T_VELIKOSTI_ID;
DROP TRIGGER T_ZAJEMCI_ID;

/*BDAS2*/

-- TABULKY
DROP TABLE LOGY;
DROP TABLE SOUBORY;
-- SEKVENCE
DROP SEQUENCE S_LOGY;
DROP SEQUENCE S_SOUBORY;
-- TRIGGERY K TABULKAM
DROP TRIGGER T_LOGY_ID;
DROP TRIGGER T_SOUBORY_ID;
-- TRIGGERY INTEGRITY
DROP TRIGGER T_ZAJEMCI_CHECK_OPRAVNENI;
DROP TRIGGER T_REZERVACE_CHECK_CAS;
DROP TRIGGER T_REZERVACE_CHECK_VALIDITU_A_STAV;
DROP TRIGGER T_VLASTNOSTI_CHECK_VALIDITU;
DROP TRIGGER T_STAVY_DELETE_CHECK_INTEGRITU;
DROP TRIGGER T_PRISLUSENSTVI_CHECK_NAZEV;
-- TRIGGERY LOGOVANI
DROP TRIGGER T_LOG_INSERT_ZAJEMCI;
DROP TRIGGER T_LOG_UPDATE_ZAJEMCI;
DROP TRIGGER T_LOG_DELETE_ZAJEMCI;
DROP TRIGGER T_LOG_INSERT_OSOBY;
DROP TRIGGER T_LOG_UPDATE_OSOBY;
DROP TRIGGER T_LOG_DELETE_OSOBY;
DROP TRIGGER T_LOG_INSERT_FIRMY;
DROP TRIGGER T_LOG_UPDATE_FIRMY;
DROP TRIGGER T_LOG_DELETE_FIRMY;
DROP TRIGGER T_LOG_INSERT_REZERVACE;
DROP TRIGGER T_LOG_UPDATE_REZERVACE;
DROP TRIGGER T_LOG_DELETE_REZERVACE;
-- POHLEDY
DROP VIEW VIEW_FIRMY;
DROP VIEW VIEW_OSOBY;
DROP VIEW VIEW_MISTNOSTI;
DROP VIEW VIEW_PATRA;
DROP VIEW VIEW_PRISLUSENSTVI;
DROP VIEW VIEW_REZERVACE;
DROP VIEW VIEW_STAVY;
DROP VIEW VIEW_UCELY;
DROP VIEW VIEW_UMISTENI;
DROP VIEW VIEW_VELIKOSTI;
DROP VIEW VIEW_ZAJEMCE;
DROP VIEW VIEW_LOGY;
DROP VIEW VIEW_SOUBORY;
DROP VIEW VIEW_PROFILOVKY;
DROP VIEW VIEW_REZERVACE_HIERARCHICKY;
DROP VIEW VIEW_ZAJEMCE_HIERARCHICKY;
-- PROCEDURY INSERTY
DROP PROCEDURE P_INSERT_FIRMU;
DROP PROCEDURE P_INSERT_OSOBU;
DROP PROCEDURE P_INSERT_MISTNOST;
DROP PROCEDURE P_INSERT_PATRO;
DROP PROCEDURE P_INSERT_PRISLUSENSTVI;
DROP PROCEDURE P_INSERT_REZERVACI_SKRZ_MISTNOST;
DROP PROCEDURE P_INSERT_REZERVACI_SKRZ_VLASTNOSTI;
DROP PROCEDURE P_INSERT_UCEL;
DROP PROCEDURE P_INSERT_UMISTENI;
DROP PROCEDURE P_INSERT_VELIKOST;
DROP PROCEDURE P_INSERT_STAV;
DROP PROCEDURE P_INSERT_LOG;
DROP PROCEDURE P_INSERT_PROFILOVKU;
-- PROCEDURY DELETY
DROP PROCEDURE P_DELETE_REZERVACI;
DROP PROCEDURE P_DELETE_MISTNOST;
DROP PROCEDURE P_DELETE_OSOBU;
DROP PROCEDURE P_DELETE_FIRMU;
DROP PROCEDURE P_DELETE_UCEL;
DROP PROCEDURE P_DELETE_UMISTENI;
DROP PROCEDURE P_DELETE_PATRO;
DROP PROCEDURE P_DELETE_VELIKOST;
DROP PROCEDURE P_DELETE_PRISLUSENSTVI;
DROP PROCEDURE P_DELETE_STAV;
DROP PROCEDURE P_DELETE_LOG;
DROP PROCEDURE P_DELETE_PROFILOVKU;
-- PROCEDURY UPDATE
DROP PROCEDURE P_UPDATE_FIRMU;
DROP PROCEDURE P_UPDATE_OSOBU;
DROP PROCEDURE P_UPDATE_HESLO;
DROP PROCEDURE P_UPDATE_UCEL;
DROP PROCEDURE P_UPDATE_UMISTENI;
DROP PROCEDURE P_UPDATE_PATRO;
DROP PROCEDURE P_UPDATE_VELIKOST;
DROP PROCEDURE P_UPDATE_PRISLUSENSTVI;
DROP PROCEDURE P_UPDATE_STAV;
DROP PROCEDURE P_UPDATE_LOG;
DROP PROCEDURE P_UPDATE_PROFILOVKU;
-- PROCEDURY OSTATNI
DROP PROCEDURE P_CHECK_DOSTUPNOST_REZERVACE;
DROP PROCEDURE P_CHECK_STAVY_REZERVACI;
DROP PROCEDURE P_CHECK_CASY_REZERVACE;
DROP PROCEDURE P_CHECK_VLASTNOSTI_PODMNOZINOU;
DROP PROCEDURE P_MAKE_LOG;
-- BALICKY
DROP PACKAGE PCKG_REZ_VLAS_MIST;
DROP PACKAGE PCKG_LOGIN;